### ISSUE TITLE
Selecting right scheme didn't work for me

### ISSUE THREAD

**Issue by rmuslimov** [vikeri/rn-cljs-tools#1]
I'm using re-natal, and my `build-ios-offline` failed with next exception:

`xcodebuild: error: The project named "FutureAppRum" does not contain a scheme named "Release". The "-list" option can be used to find the names of the schemes in the project.`

I ran `xcodebuild -list` and found scheme defined for my project: `FutureAppRum`

Replacing `Release` to `FutureAppRum` worked fine

**Comment by vikeri** [comment]
Can you check if the latest commit fixes this?
https://github.com/vikeri/rn-cljs-tools/commit/3a4e3f10bef84d57a9430369658ca7a820ee0f1c

**Comment by rmuslimov** [comment]
Worked, thanks
